os: osx
osx_image: xcode10.2

script:
  set -o pipefail &&
  travis_retry
  xcodebuild build test
  -workspace clipper.xcworkspace
-scheme clipper
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
  | xcpretty
