os: osx
osx_image: xcode10.2

script:
  ls &&
  pod install &&
  ./scripts/configure-keychain.sh &&
  security find-identity -v -p codesigning &&
  set -o pipefail &&
  travis_retry
  xcodebuild build test
  -workspace clipper.xcworkspace
  -scheme clipper
  CODE_SIGN_IDENTITY="2D57013D46DDCCA9F7DA9ACC2491E6ABD7FE1668"
  CODE_SIGNING_REQUIRED=NO
  | xcpretty
