os: osx
osx_image: xcode10.2

script:
  ls &&
  pod install &&
  ./scripts/configure-keychain.sh &&
  security find-identity -v -p codesigning &&
  set -o pipefail &&
  travis_retry
  xcodebuild build test
  -workspace clipper.xcworkspace
  -scheme clipper
  CODE_SIGN_IDENTITY="E2F32C45F58F55EA1EBEBE07243BE3ABA5D8D195"
  CODE_SIGNING_REQUIRED=NO
  | xcpretty
